version: '3'
services:
  consumer:
    build: consumer-api/
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  producer:
    build: producer/
    env_file:
      - producer/env.local
  