version: '3'
services:
  consumer:
    build: consumer-api/
    ports:
      - "5000:5000"
    depends_on: 
      - redis
  redis:
    image: "redis:alpine"
  producer:
    build: producer/
    env_file:
      - producer/env.local
    depends_on: 
      - redis
  
